inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - config/**/*
    - lib/tasks/*
    - Gemfile
    - features/**/*
    - spec/**/*
    - node_modules/**/*

# 日本語のコメントを許可
AsciiComments:
  Enabled: false

# 複数行でのlambdaでの->を許可
Lambda:
  Enabled: false

# クラスにコメントを残さないことを許可
Documentation:
  Enabled: false

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

LineLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Max: 20

FormatString:
  EnforcedStyle: percent

NumericLiterals:
  Enabled: false

RedundantReturn:
  Enabled: false

DotPosition:
  EnforcedStyle: trailing
